### ISSUE TITLE
Can you tell me what is these variable defineition?

### ISSUE THREAD

**Issue by idiotcv** [Taeyoung96/GRIL-Calib#11]
![截图 2024-09-27 11-02-27](https://github.com/user-attachments/assets/110e5172-12c1-4f71-9631-fa99da954904)

**Comment by idiotcv** [comment]
@Taeyoung96

**Comment by idiotcv** [comment]
And I faced this problem,but I don't not how to solve it.
![Uploading 截图 2024-09-27 12-33-45.png…]()

**Comment by idiotcv** [comment]
And I faced this problem,but I don't not how to solve it.
![截图 2024-09-27 12-33-45](https://github.com/user-attachments/assets/57f3dfd4-4f1f-4dd4-aa99-eb9f75b077ac)

**Comment by Taeyoung96** [comment]
@idiotcv   
Sorry for the late reply.  

The first mentioned variables are related to the initial parameters of the madgwick algorithm.  
For more information, see [this repository](https://github.com/xioTechnologies/Fusion).  
  
If your program crashes, it's most likely related to this https://github.com/Taeyoung96/GRIL-Calib/issues/9#issuecomment-2352092890
You'll need to use a tool like gdb to analyze the exact cause.

**Comment by Taeyoung96** [comment]
It will be closed if no further activity occurs.
Thanks 😄
