### ISSUE TITLE
다른 논문 평가 데이터

### ISSUE THREAD

**Issue by ssolchoi** [Taeyoung96/GRIL-Calib#20]
안녕하세요. 논문 너무 감명 깊게 잘 봤습니다.
제가 라이다-imu calibration을 공부한지 얼마되지 않아 너무 기초적인 부분일 수도 있으나 몇가지 궁금한 점이 있어 이렇게 글을 남깁니다.
현재 저는 여러 논문들을 분석하고 성능을 평가하는 중에 있습니다.

논문에 M2DGR 데이터셋으로 평가를 했다고 명시되어 있는데,
LIC[15]와 LI_init[17]은 모든 축에 대한 움직임을 가지고 calibration하는 것으로 알고 있습니다. 그럼 본 논문에서는 어떻게 주행 데이터로 평가를 했는지 너무 궁금합니다.

바쁘시겠지만 답변주시면 감사하겠습니다.

**Comment by Taeyoung96** [comment]
@ssolchoi   
Thank you for your interest in the paper.  

As you mentioned, LIC[15] and LI-Init[17] require movement for all axes, but in ground robots, this movement is limited, so we derived their results with limited data.  

Therefore, we wanted to propose in this paper that the suggested algorithm, **GRIL-Calib**, is more suitable for ground robots than LIC[15]  and LI-Init[17] .  

I hope this answers your questions.
