### ISSUE TITLE
The estimated height fluctuates frequently

### ISSUE THREAD

**Issue by ouguangjun** [Taeyoung96/GRIL-Calib#3]
Hi @Taeyoung96 ,

Thanks for your great work! 
When I test the dataset we collected and find that the estimated height fluctuates frequently and is quite different from the value we measured manually. 

I try to visualize the "/patchworkpp/ground" and find that it not only contains the ground points but also the points on the ceiling, as shown the image bellow:
![xFIGFiaCVe](https://github.com/Taeyoung96/GRIL-Calib/assets/105149931/c5841e6f-6c97-4a35-959f-66f185a94cb5)
![Nhz9kfPyEk](https://github.com/Taeyoung96/GRIL-Calib/assets/105149931/687d9048-64e9-4353-8e9c-0f81ba8de7b8)

For the parameter for the patchworkpp in the config file , I just change the "sensor_height" and do not make any other changes.  Do I need to modify anything else? The height of the imu is approximately 0.22m and the height of the lidar is 0.075m.  Looking forward to your reply.  Thanks

**Comment by ouguangjun** [comment]
I did a simple filtering on ground_points (removing ceiling point clouds) and found that  the estimated_height look good and stable , but it didn't seem to have any effect on the calibration results.

**Comment by Taeyoung96** [comment]
@ouguangjun   
Thanks for interesting our work!  

If the ground estimation is done well, the calibration results should look better.  
Does the rotation matrix output well when `verbose` is set to `true`?

Thanks,

**Comment by ouguangjun** [comment]
@Taeyoung96 
Thanks for your reply. The rotation matrix (from ground to lidar/imu) look more stable. I test GRIL-Calib and LI-init on the same sequence and find that gril-calib get better result on translation.
