### ISSUE TITLE
Ground Constraints

### ISSUE THREAD

**Issue by Mrfanxuan** [Taeyoung96/GRIL-Calib#4]
Hello, 
thank you for open-sourcing this work. 
I have a question: Does the ground constraint in this code really work in IESKF update? Does thousands of dimensional point-to-plane residual observations with three ground constraints really have a different impact on state updates?

**Comment by Mrfanxuan** [comment]
According to the code you provided, I modified and added the ground constraint in Fastlio2 during the IESKF update phase, but the result showed that it did not have any effect.

**Comment by Taeyoung96** [comment]
@Mrfanxuan 
Thanks for interesting our work!  

First of all, as you said, it is indeed true that ground plane constraints are less affected than point-to-plane residual observations.  
As a result, you can also adjust the `ground_cov` parameter in config to increase the effectiveness of ground constraints in your environment.

**Comment by Taeyoung96** [comment]
This is a stale issue, so I'll close it. Feel free to re-open if you have any questions.
