### ISSUE TITLE
Data Collection Suggestions

### ISSUE THREAD

**Issue by jedi-alindogan** [Taeyoung96/GRIL-Calib#6]
Hi

Would it be possible to provide some suggestions for data collection in the readme? E.g. "Rotate in all axes; make figure 8 trajectories" etc.

**Comment by Taeyoung96** [comment]
@jedi-alindogan   
Thanks for interesting our work!  

For data collection, we recommend that you first run your experiment on a flat surface with plenty of ground visibility.  
Also, since the algorithm relies on acceleration, we recommend that the robot's motion does not change rapidly.

**Comment by Taeyoung96** [comment]
It will be closed if no further activity occurs.
Thanks 😄
