### ISSUE TITLE
yaw not accurate

### ISSUE THREAD

**Issue by HXPRedBlue** [Taeyoung96/GRIL-Calib#7]
Hello
First of all, thank you very much for your work.
I encountered such a problem when performing calibration. I collected data on a flat ground and performed uniform circular motion. I found that my roll and pitch calibrations are relatively accurate, but the calibrated data for yaw, x, y, and z deviate relatively large from the actual values. I looked at papers and codes and found that when ground constraints are applied, the vehicle is required to move at a uniform speed. However, the acceleration constraint initially requires variable-speed motion. If it is uniform speed, then the acceleration is 0, and any component of acceleration is 0. Then it will not play a constraining role because no matter what yaw is, the acceleration constraint is always valid. I don't know if my thinking is correct.
How to solve the contradiction between acceleration constraint and ground constraint?

**Comment by Taeyoung96** [comment]
@HXPRedBlue   
Thanks for interesting our work!  

As you said, if you move at a uniform speed, the acceleration will be zero.  
What I meant was that you shouldn't change your motion abruptly to reduce noise. Also, when you get data for your experiment, take an '8' shaped motion, not a circular motion, and you'll have accumulated enough data.  

I hope this answers your question.

**Comment by Taeyoung96** [comment]
It will be closed if no further activity occurs.
Thanks 😄
