### ISSUE TITLE
Port to ROS 2 (Humble)

### ISSUE THREAD

**Issue by vlacorre** [Taeyoung96/GRIL-Calib#8]
Hi @Taeyoung96!

Thank you for sharing this very useful software :)

I was wondering if you had plans to port it to ROS 2?
I would be ready to spend some time porting it if you're interested!

Best,
Vivien

**Comment by Taeyoung96** [comment]
@vlacorre   
Thanks for interesting our work!  

I think porting to ROS2 is something we really need to do, I have some code that I've changed to ROS2,  
but it's currently untested and probably buggy. 

If I were to create a separate ROS2 branch and provide the code, would you be willing to experiment with it and let me know if there are any bugs?

**Comment by vlacorre** [comment]
Absolutely, just let me know when it's ready :)

**Comment by Taeyoung96** [comment]
@vlacorre   
Now I've created a [humble](https://github.com/Taeyoung96/GRIL-Calib/tree/humble) branch! :smile:   
First, I created a config and launch example for `velodyne`.   
I'd love it if you could modify it for your own use and test it.

**Comment by vlacorre** [comment]
Hi @Taeyoung96,

I tested the package and it run well the first time, but then when I retried to start the launch file and restart my bag file, rviz did not show anything and the only console output was the following:

```
~/ros2_ws# ros2 launch gril_calib mapping_velodyne.launch.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-09-23-12-20-59-611292-VL-Laptop-4134
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [gril_calib_exec-1]: process started with pid [4135]
[INFO] [rviz2-2]: process started with pid [4137]
[rviz2-2] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[gril_calib_exec-1] Multi thread started 
[gril_calib_exec-1] lidar_type: 2
[gril_calib_exec-1] LiDAR-only odometry starts.
[gril_calib_exec-1] Operating patchwork++...
[gril_calib_exec-1] [INFO] [1727094059.700201603] [patchworkpp]: Inititalizing PatchWork++...
[gril_calib_exec-1] Sensor Height: 0.85
[gril_calib_exec-1] Num of Iteration: 3
[gril_calib_exec-1] Num of LPR: 20
[gril_calib_exec-1] Num of min. points: 10
[gril_calib_exec-1] Seeds Threshold: 0.3
[gril_calib_exec-1] Distance Threshold: 0.125
[gril_calib_exec-1] Max. range:: 4
[gril_calib_exec-1] Min. range:: 1
[gril_calib_exec-1] Normal vector threshold: 0.707
[gril_calib_exec-1] adaptive_seed_selection_margin: -1.2
[gril_calib_exec-1] Num. zones: 4
[gril_calib_exec-1] Num. sectors: 16, 32, 54, 32
[gril_calib_exec-1] Num. rings: 3, 3, 3, 3
[gril_calib_exec-1] elevation_thr_: 0.1000, 0.2000, 0.4000, 0.6000 
[gril_calib_exec-1] flatness_thr_: 0.0000, 0.0000, 0.0000, 0.0000 
[gril_calib_exec-1] INITIALIZATION COMPLETE
[gril_calib_exec-1] ~~~~/root/ros2_ws/src/ file opened
[gril_calib_exec-1] [INFO] [1727094059.708538260] [laser_mapping]: Node init finished.
[rviz2-2] [INFO] [1727094059.807339114] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1727094059.807414371] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-2] [INFO] [1727094059.824738306] [rviz2]: Stereo is NOT SUPPORTED
```

Does the output seem weird to you?

**Comment by Taeyoung96** [comment]
@vlacorre   
Thanks for testing our work!  

There's nothing wrong with the output you've shown so far,  
but it's strange that there's no output for the [Acceleration norm](https://github.com/Taeyoung96/GRIL-Calib/blob/35dd865bab82df3addcb1cbdaf2c09dc03f644d2/src/laserMapping.cpp#L502).

Did you set the config to your own environment?  
You need to make sure you have the topic name correct, the height of the IMU sensor, etc.   

Also, the angular velocity unit for the IMU should be rad/s.

**Comment by Taeyoung96** [comment]
It will be closed if no further activity occurs.
Thanks 😄
